version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile.prod
      context: ./api
    container_name: book-api
    command: npm run start:prod
    restart: unless-stopped
    environment:
      - PORT=3000
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB_NAME=book-api
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=api_db
    ports:
      - 3000:3000
    depends_on:
      - api_db
    networks:
      - book-api-network
    volumes:
      - ./api/src:/usr/src/app/src

  api_db:
    image: postgres:alpine
    container_name: book-api-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=book-api
    volumes:
      - postgres-db_api:/data/db
    ports:
      - 5432:5432
    networks:
      - book-api-network

  nginx:
    image: nginx:stable-alpine
    container_name: book-api-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
    networks:
      - book-api-network

volumes:
  postgres-db_api:

networks:
  book-api-network:
    driver: bridge
