version: '3'

services:
  api:
    build: ./api
    container_name: book-api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3000
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB_NAME=book-api
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=api_db
    ports:
      - 3000:3000
    depends_on:
      - api_db
    networks:
      - book-api-network

  api_db:
    image: postgres
    container_name: book-api-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=book-api
    volumes:
      - postgres-db_api:/data/db
    ports:
      - 5432:5432
    networks:
      - book-api-network

volumes:
  postgres-db_api:

networks:
  book-api-network:
    driver: bridge
