const DEFAULT_BOOK_LIMIT = 20;
const LIMIT_REQ_SIZE = '10mb';
const API_VERSION = '0.0.1';
const MAX_BOOK_TEXT_LENGHT = 10000000;

export {
  DEFAULT_BOOK_LIMIT,
  LIMIT_REQ_SIZE,
  API_VERSION,
  MAX_BOOK_TEXT_LENGHT,
};
